### ISSUE TITLE
Add pdf of schematic

### ISSUE THREAD

**Issue by Teslafly** [adafruit/Adafruit-QT-Py-ESP32-C3-PCB#1]
Can a pdf if the schematic be added so one doesn't have to have eagle installed to view it?

**Comment by tannewt** [comment]
Images of the schematic are available in product learn guides: https://learn.adafruit.com/adafruit-qt-py-esp32-c3-wifi-dev-board/downloads#schematic-and-fab-print-3113127

I've also used KiCad to view the files without trouble.
